extends Resource

const REQUIRED_PATHS: Array[String] = [
	"res://assets/title/title_scene_desktop.png",
	"res://assets/title/title_scene_mobile.png",
	"res://assets/title/protos_harvest_title_desktop.png",
	"res://assets/title/protos_harvest_title_mobile.png",
	"res://assets/title/protos_harvest_icon.png",
	"res://assets/walker/grunt_sprite_atlas.png",
	"res://assets/ui/modules/aftershock.png",
	"res://assets/ui/modules/storm_seal.png",
	"res://assets/vfx/pickups/worm_core.png",
	"res://assets/vfx/worm/ridge_segment.png",
	"res://assets/vfx/worm/breach_plume.png",
	"res://assets/walker/grunt_sprite_atlas.png",
	"res://assets/textures/terrain/oasis_wetland.png",
	"res://assets/textures/terrain/dark_mud.png",
	"res://assets/enemies/mud_skimmer.png",
	"res://assets/textures/terrain/tundra_snow.png",
	"res://assets/textures/terrain/blue_ice.png",
	"res://assets/enemies/rime_stalker.png",
	"res://assets/textures/terrain/lava_basalt.png",
	"res://assets/textures/terrain/volcanic_ash.png",
	"res://assets/textures/terrain/lava_flow.png",
	"res://assets/textures/terrain/woodland_grass.png",
	"res://assets/textures/terrain/farm_soil.png",
	"res://assets/enemies/cinder_crawler.png",
	"res://assets/destructibles/wetland_mangrove.png",
	"res://assets/destructibles/wetland_stump.png",
	"res://assets/destructibles/frozen_snow_rock.png",
	"res://assets/destructibles/frozen_pine.png",
	"res://assets/destructibles/lava_basalt_chimney.png",
	"res://assets/destructibles/lava_obsidian_cluster.png",
	"res://assets/outposts/ancient_ruin.png",
	"res://assets/outposts/ancient_temple.png",
	"res://assets/outposts/ancient_ziggurat.png",
	"res://assets/outposts/ancient_palace.png",
	"res://assets/outposts/ancient_safehouse.png",
	"res://assets/woodland/woodland_broadleaf_tree.png",
	"res://assets/woodland/woodland_conifer_tree.png",
	"res://assets/woodland/woodland_pond.png",
	"res://assets/vfx/juice/impact_contact.png",
	"res://assets/vfx/juice/footstep_dust.png",
	"res://assets/vfx/juice/charge_ready.png",
	"res://assets/vfx/juice/relay_flare.png",
	"res://assets/vfx/juice/pickup_spark.png",
	"res://assets/tools/protos_hoe_spritesheet.png",
	"res://assets/tools/protos_water_spritesheet.png",
	"res://assets/ui/tools/icon_hoe.png",
	"res://assets/ui/tools/icon_watering_tool.png",
	"res://assets/ui/tools/icon_axe.png",
	"res://assets/ui/tools/icon_pick.png",
	"res://assets/ui/tools/icon_seed_pouch.png",
	"res://assets/crops/crop_glowroot_stages.png",
	"res://assets/crops/crop_coilbean_stages.png",
	"res://assets/crops/crop_ironturnip_stages.png",
	"res://assets/crops/crop_rainleaf_stages.png",
	"res://assets/crops/crop_starbloom_stages.png",
	"res://assets/crops/crop_sunpod_stages.png",
	"res://assets/flora/flora_starflower_stages.png",
	"res://assets/flora/flora_brambleberry_stages.png",
	"res://assets/flora/flora_sunpear_stages.png",
	"res://assets/flora/flora_wildwheat_stages.png",
	"res://assets/flora/flora_cotton_stages.png",
	"res://assets/flora/wild_starflower_mature.png",
	"res://assets/flora/wild_brambleberry_mature.png",
	"res://assets/flora/wild_sunpear_mature.png",
	"res://assets/flora/wild_wildwheat_mature.png",
	"res://assets/flora/wild_cotton_mature.png",
	"res://assets/props/farm_shipping_bin.png",
	"res://assets/props/home_storage_crate.png",
	"res://assets/props/tool_upgrade_bench.png",
	"res://assets/props/machine_furnace.png",
	"res://assets/props/machine_irrigation_pump.png",
	"res://assets/facilities/facility_home.png",
	"res://assets/facilities/facility_greenhouse.png",
	"res://assets/facilities/facility_workshop.png",
	"res://assets/facilities/facility_clinic_kitchen.png",
	"res://assets/residents/resident_lyra.png",
	"res://assets/residents/resident_rook.png",
	"res://assets/residents/resident_mira.png",
	"res://assets/livestock/livestock_mossback_spritesheet.png",
	"res://assets/livestock/livestock_coilhen_spritesheet.png",
	"res://assets/livestock/livestock_rustsnout_spritesheet.png",
]


func validate_required() -> bool:
	for path: String in REQUIRED_PATHS:
		if not ResourceLoader.exists(path):
			return false
		var texture: Texture2D = load(path) as Texture2D
		if texture == null or texture.get_width() < 32 or texture.get_height() < 32:
			return false
	return true


func get_required_paths() -> Array[String]:
	return REQUIRED_PATHS.duplicate()
